repos:
      - repo: https://github.com/PyCQA/isort
        rev: 5.6.4
        hooks:
              - id: isort
                alias: isort
                name: isort
                args: ["--settings-path=setup.cfg"]
                files: examples/.*
                exclude: __init__.py$
                types: [text]
                types_or: [python]
      - repo: https://github.com/psf/black
        rev: 19.10b0
        hooks:
              - id: black
                files: examples/.*
      - repo: https://github.com/PyCQA/flake8
        rev: 3.8.3
        hooks:
              - id: flake8
                alias: flake8
                name: flake8
                args: ["--config=.flake8"]
                files: python/.*\.py$
      # - repo: https://github.com/PyCQA/pydocstyle
      #   rev: 6.1.1
      #   hooks:
      #         - id: pydocstyle
      #           args: ["--config=.flake8"]

default_language_version:
      python: python3
